#!/bin/sh

# - lists containers
# - filters by peco
# - bash via docker exec -it

CONTAINER_ID=$(docker ps | tail -n +2 | peco | awk '{print $1}')
if [ -n "$CONTAINER_ID" ]; then
  docker exec -it $CONTAINER_ID bash
fi
