#!/bin/sh -x

#This script removes Mono from an OS X System.  It must be run as root

/bin/rm -r /Library/Frameworks/Mono.framework

/bin/rm -r /Library/Receipts/MonoFramework-*

for dir in /usr/bin /usr/share/man/man1 /usr/share/man/man3 /usr/share/man/man5; do
  (cd ${dir};
  for i in `ls -al | grep /Library/Frameworks/Mono.framework/ | awk '{print $9}'`; do
    /bin/rm ${i}
  done);
done
